.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. renaiss_qt test_renaiss_qt
clean: FORCE
	$(MAKE) -C .. renaiss_qt_clean test_renaiss_qt_clean
check: FORCE
	$(MAKE) -C .. test_renaiss_qt_check
renaiss-qt renaiss-qt.exe: FORCE
	 $(MAKE) -C .. renaiss_qt
apk: FORCE
	$(MAKE) -C .. renaiss_qt_apk
